/* Generated by Yosys 0.20+22 (git sha1 c26b2bf54, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_piso(clk, load, data_in, data_out);
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input clk;
  wire clk;
  input [3:0] data_in;
  wire [3:0] data_in;
  output data_out;
  wire data_out;
  input load;
  wire load;
  wire [3:0] q;
  sky130_fd_sc_hd__mux2_1 _14_ (
    .A0(_07_),
    .A1(_12_),
    .S(_09_),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(_06_),
    .A1(_11_),
    .S(_09_),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(_05_),
    .A1(_10_),
    .S(_09_),
    .X(_01_)
  );
  sky130_fd_sc_hd__or2_0 _17_ (
    .A(_09_),
    .B(_08_),
    .X(_04_)
  );
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(q[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_13_),
    .Q(q[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(q[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(q[1])
  );
  assign data_out = q[0];
  assign _07_ = data_in[2];
  assign _12_ = q[3];
  assign _09_ = load;
  assign _00_[2] = _03_;
  assign _06_ = data_in[1];
  assign _11_ = q[2];
  assign _00_[1] = _02_;
  assign _05_ = data_in[0];
  assign _10_ = q[1];
  assign _00_[0] = _01_;
  assign _08_ = data_in[3];
  assign _13_ = _04_;
endmodule
